{% set name = "phyddle" %}
{% set version = "0.2.1" %}

package:
  name: {{name}}
  version: {{version}}

source:
  # get URL & SHA for new version from: https://pypi.org/project/phyddle/#modal-close
  url: https://files.pythonhosted.org/packages/d1/c8/a13269d5e2dd3ee7c2a5322c05be0272ee0286a658a52dcf6b91321a7daf/phyddle-0.2.1.tar.gz
  sha: f1f0b11a9f3066b94091b2cade62bbed94a68f566839c6e72a5563dd98ff3c55

build:
  noarch: generic
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - git
    - git-lfs
    - hatchling
  run:

    #'python>=3.11' 'dendropy>=4.6' 'tensorflow>=2.12' numpy=1.23 pandas=2.0 scipy=1.11 joblib=1.2 tqdm=4.65 h5py=3.8 keras=2.12  matplotlib=3.7 pypdf=3.12 Pillow=10.0 scikit-learn=1.2 graphviz python-graphviz pydot

    - python
    - dendropy >=4.5
    - graphviz
    - h5py
    - keras
    - matplotlib >=3.7
    - numpy >=1.22
    - pandas >=2.0
    - pydot
    - pypdf
    - python-graphviz
    - scikit-learn >=1.2
    - scipy >=1.11
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - phyddle
  commands:
    - phyddle --help

about:
  home: https://mlandis.github.io/phyddle
  dev_url: http://github.com/mlandis/phyddle
  doc_url: https://mlandis.github.io/phyddle
  license: MIT
  license_family: MIT
  summary: Software to fiddle around with deep learning for phylogenetic models
